Repository wecode-bootcamp-korea/17-2nd-WantUs-frontend, pull requests merged in 2021-03, with the labels that each got.

#5 [17기 이미경] Nav바 UI/기능 리뷰 반영 완료
  package-lock.json
  package.json
  public/data/mockdata.json
  public/data/navData.json
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Components/Nav/NavDetail.js
  src/Components/Nav/navData.js
  src/Pages/Main.js
  src/Routes.js
Labels: Status: Accepted

#1 [17기 이미경] Footer 리뷰 반영 완료 (data map 분리)
  public/images/footer/logo_wanted.png
  src/Components/Footer/Footer.js
  src/Components/Footer/FooterData.js
  src/Components/Nav/Nav.js
  src/Routes.js
Labels: Status: Accepted

#10 [17기 이미경] Footer페이지 CSS 및 로고 추가 수정 완료 🎈 (두번째 브랜치) - 머지요청
  public/images/footer/logo.png
  public/images/footer/logo_wanted.png
  src/Components/Footer/Footer.js
  src/Routes.js
Labels: Status: Accepted

#12 [17기 이미경] Nav페이지 CSS 추가 수정 완료 🎈 (두번째 브랜치) - 머지요청
  src/Components/Nav/Nav.js
Labels: Status: Accepted

#13 [17기 이미경] Footer페이지 CSS 추가 수정 완료 🎈 (세번째브랜치) - 머지요청
  src/Components/Footer/Footer.js
Labels: Status: Accepted

#3 [17기 이미경] Newintro 메인 페이지 UI/기능 리뷰 반영 완료!
  src/Pages/Main.js
  src/Pages/Newintro/Components/NewintroCenter.js
  src/Pages/Newintro/Components/NewintroData.js
  src/Pages/Newintro/Newintro.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#7 [17기 이미경] Main 페이지 컴포넌트/Map 구현 완료
  package-lock.json
  package.json
  public/data/CareerData.json
  public/data/PositionData.json
  src/Pages/Images/recommend.JPG
  src/Pages/Main/Components/AcceptedPositionBox.js
  src/Pages/Main/Components/CareerBox.js
  src/Pages/Main/Components/NewhireBox.js
  src/Pages/Main/Components/Positions.js
  src/Pages/Main/Components/Slider.js
  src/Pages/Main/Components/SliderData.js
  src/Pages/Main/Components/ThemeBox.js
  src/Pages/Main/Components/ThisWeekBox.js
  src/Pages/Main/Main.js
  src/Routes.js
Labels: Status: 리뷰 요청

#4 [17기 변미현 ] 리뷰반영 완료, 스크롤 기능, 백엔드 통신 완료(머지요청)
  public/data/JobData.json
  public/data/subCategory.json
  src/Pages/Explore/Components/Bookmark/BookmarkLink.js
  src/Pages/Explore/Components/Filter/Filter.js
  src/Pages/Explore/Components/Job/Job.js
  src/Pages/Explore/Components/Job/JobContent.js
  src/Pages/Explore/Components/Slider/Slide.js
  src/Pages/Explore/Explore.js
  src/Routes.js
  src/Styles/GlobalStyles.js
  src/Styles/theme.js
  src/config.js
  src/context.js
  src/index.js
Labels: Status: Accepted

#14 [17기 변미현] 리뷰반영 완료, 통신 완료.
  public/data/allData.json
  public/data/filterData.json
  src/BoardProvider.js
  src/Pages/Explore/Components/Filter/Filter.js
  src/Pages/Explore/Components/Job/Job.js
  src/Pages/Explore/Components/Job/JobContent.js
  src/Pages/Explore/Explore.js
  src/Pages/Modal/CareerModal.js
  src/Pages/Modal/LocationModal.js
  src/Pages/Modal/LocationModalCategory.js
  src/Pages/Modal/ModalHeader.js
  src/Pages/Modal/TagModal.js
  src/Pages/Modal/TagModalCategory.js
  src/Pages/Modal/TagSelector.js
  src/Routes.js
  src/Styles/theme.js
  src/config.js
Labels: Status: Accepted

#2 [17기 유샘솔] Login | conflict 해결 완료 👌🏻
  public/index.html
  src/Pages/Login/Login.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#9 [17기 이미경] CV 페이지 구현 중 (writing page, input창 기능 구현 완료) (머지요청)
  package-lock.json
  package.json
  public/data/CVData.json
  public/data/CVwriteData.json
  src/Components/Nav/Nav.js
  src/Components/Nav/NavDetail.js
  src/Pages/CV/CV.js
  src/Pages/CV/CVData.js
  src/Pages/CV/CVdetail.js
  src/Pages/CV/CVwrite.js
  src/Pages/CV/CVwriteBottom.js
  src/Routes.js
Labels: Status: Accepted

#6 [17기 유샘솔] 상세페이지 | conflict 해결 완료 👌🏻
  public/data/JobData.json
  public/data/JobDetailData.json
  public/data/myWantedData.json
  src/Pages/JobDetail/JobDetail.js
  src/Pages/JobDetail/components/JobList/Job.js
  src/Pages/JobDetail/components/JobList/JobList.js
  src/Routes.js
  src/Styles/theme.js
Labels: Status: Accepted

#11 [17기 유샘솔] Mypage | conflict 해결 완료 👌🏻 / 마이페이지 정보수정을 위해 contextAPI 로 state 관리 추가
  public/data/bookmarkData.json
  public/data/forLayout.json
  public/data/likesData.json
  src/BoardProvider.js
  src/Context/profile.js
  src/Pages/Mypage/MyProfile.js
  src/Pages/Mypage/Mypage.js
  src/Pages/Mypage/components/EditPage.js
  src/Pages/Mypage/components/Profile.js
  src/Pages/Mypage/components/ResumeSelectModal.js
  src/Pages/Mypage/components/SetProfile.js
  src/Pages/Mypage/components/UserData.js
  src/Routes.js
  src/Styles/theme.js
  src/index.js
Labels: Status: Accepted

#15 [17기 변미현] 비동기 현상으로 인한 밀림현상 해결!
  src/BoardProvider.js
  src/Routes.js
Labels: Status: 리뷰 요청

#18 [17기 유샘솔] 머지된 브랜치에서 fetch 수정했습니다.
  src/BoardProvider.js
  src/Pages/JobDetail/JobDetail.js
  src/Pages/JobDetail/components/JobList/Job.js
  src/Pages/JobDetail/components/JobList/JobList.js
  src/Pages/Login/Login.js
  src/Pages/Mypage/components/UserData.js
  src/config.js
Labels: Status: Accepted

#17 [17기 변미현] 백엔드 통신을 위한 로직 수정
  src/BoardProvider.js
  src/Pages/Explore/Components/Filter/Filter.js
  src/Pages/Explore/Components/Job/JobContent.js
  src/Pages/JobDetail/components/JobList/Job.js
  src/Pages/Modal/CareerModal.js
  src/Pages/Modal/LocationModal.js
  src/Pages/Modal/LocationModalCategory.js
  src/Pages/Modal/ModalHeader.js
  src/Pages/Modal/TagModal.js
  src/Routes.js
Labels: Status: 리뷰 요청, Status: 컨플릭트 해결 요청

#16 [17기 이미경] CV 페이지 추가 구현 중 (삭제/추가/첨부 기능 구현 중)
  src/Pages/CV/CV.js
  src/Pages/CV/CVdetail.js
  src/Pages/CV/CVwrite.js
  src/Routes.js
Labels: Status: 리뷰 요청

#19 [17기 변미현] 최종 완료.
  src/BoardProvider.js
  src/Components/Nav/LoginButton.js
  src/Components/Nav/Nav.js
  src/Components/Nav/NavDetail.js
  src/Context/profile.js
  src/Pages/CV/CV.js
  src/Pages/CV/CVdetail.js
  src/Pages/CV/CVwrite.js
  src/Pages/Explore/Components/Job/JobContent.js
  src/Pages/JobDetail/JobDetail.js
  src/Pages/JobDetail/components/JobList/JobList.js
  src/Pages/Login/Login.js
  src/Pages/Main/Components/AcceptedPositionBox.js
  src/Pages/Main/Components/NewhireBox.js
  src/Pages/Main/Components/Positions.js
  src/Pages/Main/Components/ThisWeekBox.js
  src/Pages/Modal/LocationModalCategory.js
  src/Pages/Mypage/components/EditPage.js
  src/Pages/Mypage/components/Profile.js
  src/Pages/Mypage/components/ResumeSelectModal.js
  src/Pages/Mypage/components/SetProfile.js
  src/Pages/Mypage/components/UserData.js
  src/config.js
Labels: Status: 리뷰 요청
